### ISSUE TITLE
Design Database

### ISSUE THREAD

**Issue by nhom1102024** [nhom1102024/MockProject_102024_Nhom1#79]
- các bạn cùng nhau làm ERD bằng link sau 
`https://lucid.app/lucidchart/793327dc-a69c-4d05-b6e6-ee5710e5c593/edit?viewport_loc=-208%2C-210%2C2119%2C1031%2C0_0&invitationId=inv_03ccbff5-bf45-435b-8aa5-4e48266d09ce`
- có thể tham khảo các link sau để design database với lucid chart
```bash 
https://www.youtube.com/watch?v=xsg9BDiwiJE&list=PLUoebdZqEHTxpGCwKrb82cIvHNoNaBb4R
https://youtu.be/XkqciOtQUCI?si=3SVCckOPPTeaUXMd
```
- sau khi làm xong (ít nhất phải làm) thì comment done để mình tổng hợp lại nha, mình sẽ tự kéo qua task qua done
- các bạn dev, ba, tester thảo luận mạnh tay lên nhé !!!
* note: khi làm nhớ viết task vào workbreakdown, sau khi làm xong đẩy những gì mình làm lên gg drive cá nhân để mentor review

**Comment by Dong123333** [comment]
done!

**Comment by hovanthang2503** [comment]
done!

**Comment by Ducchinh96** [comment]
done!
