### ISSUE TITLE
Continue to fig figma UI

### ISSUE THREAD

**Issue by nhom1102024** [nhom1102024/MockProject_102024_Nhom1#80]
-  mình đã chia task cho các các bạn ở link : `https://docs.google.com/spreadsheets/d/16fXfZCgJ3EKpnYaPgTRtXBlJkDgSxFJS/edit?gid=1483205768#gid=1483205768`
- sau khi xong task comment done ở issue này và check vào box ở link trên để mình biết các bạn làm xong nha
- vẽ các màn hình ở đúng các role trên phần page trong figma, sau khi vẽ xong có thể nhận các task bên dứới để làm tiếp nha
- tất cả đều phải làm làm ít làm nhiều, vẽ xấu vẽ đẹp cũng đều phải làm để có task ngày hôm này nhé
- về phần note bên phải các bạn nhận vẽ figma trước đó xem qua và sửa lại yêu cầu cho đúng
- cứ search các ui trên mạng làm theo, sáng tạo mà làm, làmm đại đi các bạn :))
- à tên màn hình đặt theo tên của file review cho dể hình dung nha 
- không cần phải kéo task qua done, khi tất cả làm xong mình sẽ tự kéo.
`https://docs.google.com/spreadsheets/d/1F_1rujUhPiy5m5xKHGiqvCzDMMsHz3A_hOOOQmn8DNA/edit?gid=527293738#gid=527293738` . các bạn đã vẽ trước đó sửa tên lại.
### finish

**Comment by seaesa** [comment]
done !!!

**Comment by honhuquy** [comment]
done

**Comment by tnuong** [comment]
done

**Comment by thuyhang2401** [comment]
done

**Comment by Thao2303** [comment]
done

**Comment by TTThanhGiang** [comment]
done

**Comment by ldtdung20it6** [comment]
done

**Comment by thongmloe** [comment]
done

**Comment by TrinhCongHuy** [comment]
done

**Comment by TanHenOtto** [comment]
done
