### ISSUE TITLE
All Member Fix Design Database

### ISSUE THREAD

**Issue by nhom1102024** [nhom1102024/MockProject_102024_Nhom1#82]
### nhiệm vụ chính của ngày hôm nay tất cả thành viên làm ERD qua link sau:
- link 1: *https://lucid.app/lucidchart/793327dc-a69c-4d05-b6e6-ee5710e5c593/edit?invitationId=inv_03ccbff5-bf45-435b-8aa5-4e48266d09ce&page=0_0*
- link 2: *https://lucid.app/lucidchart/7e0dd81f-e8b0-4f36-86a5-828c6ca5df5d/edit?invitationId=inv_4a91e524-4056-4d43-ba16-48bccd5949eb&page=0_0#*
- mng clone link 1 về máy của mình và điền các field của table thảm khảo ở folder requiment VN của nhóm + với sáng kiến của mình nha: 
- các bạn làm database ở link này: *https://docs.google.com/spreadsheets/d/16fXfZCgJ3EKpnYaPgTRtXBlJkDgSxFJS/edit?gid=1483205768#gid=1483205768* xem gộp với link 1 và bổ sung thêm phần của mình nha
- mng làm theo table đã chia ở link chia task figma của nhóm và có sáng kiến gì ở các table khác điền vào lun nhé. sau khi làm xong phần của mình mỗi ng làm luôn 3 role chưa chia bên dưới nha
- link chia task figma: *https://docs.google.com/spreadsheets/d/16fXfZCgJ3EKpnYaPgTRtXBlJkDgSxFJS/edit?gid=1483205768#gid=1483205768*
- tất cả đều phải làm, làm ít làm nhiều đều phải làm để có task cho ngày hôm đó nhé
- sau khi làm xong mng comment done và <strong>share public link của mình và export file ảnh đã làm nha gửi vào comment nha</strong> để mình tổng hợp lại.
- không cần phải đóng issue hay kéo qua done, cuối ngày mình sẽ tự kéo.
- có bất cứ câu hỏi nào hãy thảo luận trom nhóm nhé
* <strong>note</strong>: khi có task mng nhớ ghi task vào workbreakdown nha, khi làm xong thì đẩy những gì mình làm được lên gg drive cá nhân để mentor review.
<strong>deadline: 12h trưa nay</strong>

**Comment by NgaAnhNguyen** [comment]
https://lucid.app/lucidchart/ae368f64-53a2-44a4-8c1c-ae6ec0dec08e/edit?invitationId=inv_970a4460-d683-48d1-ad74-d64202226574
![Image](https://github.com/user-attachments/assets/9fd94fec-9f0d-4dd1-bd8a-2a44b66b1d91)

**Comment by haiezdev** [comment]
https://lucid.app/lucidchart/bcd9e295-a091-4412-aa64-4596b15185fe/edit?viewport_loc=-3609%2C818%2C2560%2C1152%2C0_0&invitationId=inv_1c42ee4c-e5f7-4fc9-a9c5-75d93af25e1b
![Copy](https://github.com/user-attachments/assets/ecd083ea-6877-4f6b-84d6-18b2dc66e9a9)

**Comment by Thao2303** [comment]
https://lucid.app/lucidchart/056e4564-c79f-4809-bfae-8d4dea98ac18/edit?viewport_loc=-1016%2C242%2C3454%2C1598%2C0_0&invitationId=inv_49458568-5ea9-4c65-adf6-69b3e808be36
![Thao_MockProject_DB_Group1](https://github.com/user-attachments/assets/74657014-d513-4943-a074-017f0a3f3f66)

**Comment by tuankie102** [comment]
add new entity: fines and relationship to bill

https://lucid.app/lucidchart/3c83986d-d950-42ce-88da-91a11706f7f9/edit?view_items=w5Rgd77Y6_i6&invitationId=inv_02f2cad6-6953-449f-a284-696e657e1856

![image](https://github.com/user-attachments/assets/01e8c6dc-bbd9-406b-b564-a268474b73d4)

**Comment by TTThanhGiang** [comment]
https://lucid.app/lucidchart/7309b47b-ff75-4659-843b-1d3df64ded61/edit?view_items=f9QgomeEDrUb&invitationId=inv_9cfb88ed-a0be-4c06-87df-c68dd05e4355
![Image](https://github.com/user-attachments/assets/81e997e2-e30c-4c3a-8f03-2aaf54475a26)

**Comment by thongmloe** [comment]
[https://lucid.app/lucidchart/e5523b1a-1527-4788-934a-b8d241956ca1/edit?beaconFlowId=2F31D75EBD385E4D&invitationId=inv_a50ab992-10f3-4d30-8d70-b80a69fc810c&page=0_0#](https://lucid.app/lucidchart/e5523b1a-1527-4788-934a-b8d241956ca1/edit?beaconFlowId=2F31D75EBD385E4D&invitationId=inv_a50ab992-10f3-4d30-8d70-b80a69fc810c&page=0_0#)
![Blank diagram](https://github.com/user-attachments/assets/430b1d74-8e61-4e50-93c4-77c49907626a)

**Comment by hovanthang2503** [comment]
https://lucid.app/lucidchart/4296b1df-ce52-4a49-b753-31b2399a785c/edit?viewport_loc=-10463%2C-2411%2C11151%2C4802%2C0_0&invitationId=inv_51e1869a-5264-4a11-9756-95baae68dc78
[![Image](https://github.com/user-attachments/assets/146110dc-7976-4571-a84b-f04fc55db41d)
](url)

**Comment by hovanthang2503** [comment]
https://lucid.app/lucidchart/4296b1df-ce52-4a49-b753-31b2399a785c/edit?viewport_loc=-10463%2C-2411%2C11151%2C4802%2C0_0&invitationId=inv_51e1869a-5264-4a11-9756-95baae68dc78
![Image](https://github.com/user-attachments/assets/c608b699-de38-4677-8f16-d48f736ef615)

**Comment by thuyhang2401** [comment]
https://lucid.app/lucidchart/b90b06ed-0ce8-4f0b-ad82-a54745af34a4/edit?invitationId=inv_0af79b1c-0e4b-44d6-9683-2a1a96e016cb
![MockProject_DB_Group1_ThuyHang](https://github.com/user-attachments/assets/1cc225f6-c8a3-444c-afdf-816bbbfbf37d)

**Comment by tnuong** [comment]
https://lucid.app/lucidchart/db06ae54-5c92-49f7-a654-db198864dce6/edit?page=0_0&invitationId=inv_0f39ab9c-15cb-4c56-bf5b-02ec1ccc9b38#

**Comment by tnuong** [comment]
https://lucid.app/lucidchart/db06ae54-5c92-49f7-a654-db198864dce6/edit?page=0_0&invitationId=inv_0f39ab9c-15cb-4c56-bf5b-02ec1ccc9b38#
![database](https://github.com/user-attachments/assets/4fec9dad-b416-4182-a25a-386c8de350c1)

**Comment by Dong123333** [comment]
https://lucid.app/lucidchart/8c0dd889-7695-4e12-aaa4-9ba28175b3f3/edit?beaconFlowId=E3B8FE1DA831BE3A&invitationId=inv_b36f2f7d-aec3-43c1-9d0f-65f09931ccb1&page=0_0#

**Comment by seaesa** [comment]
done !!
https://lucid.app/lucidchart/bab7c546-02a0-4e2f-875d-414e6b6914b1/edit?viewport_loc=-1908%2C-260%2C4440%2C2160%2C0_0&invitationId=inv_137ebcb9-7569-460c-bfcd-68352915e7ca
![Ngochai_Mocproject](https://github.com/user-attachments/assets/f0f447c8-bfe0-455f-a542-3365dfcab1b0)

**Comment by HuyNgo000** [comment]
https://lucid.app/lucidchart/7e0dd81f-e8b0-4f36-86a5-828c6ca5df5d/edit?viewport_loc=-3125%2C3639%2C2560%2C1114%2C0_0&invitationId=inv_4a91e524-4056-4d43-ba16-48bccd5949eb
![Screenshot 2024-10-11 134459](https://github.com/user-attachments/assets/edfc4bbe-acd6-4f89-b990-bd3d59f1bdad)

**Comment by nqcuong2003** [comment]
Done!!
https://lucid.app/lucidchart/b4489f93-9e1c-4f38-8544-26eea800bd25/edit?view_items=doTgfmhHWQ9o&invitationId=inv_6aa523f9-7f3f-4fcf-b27d-3e1994d0fbb1
![image](https://github.com/user-attachments/assets/73933bf8-d330-44c0-9a76-dc99b1c1a792)

**Comment by ldtdung20it6** [comment]
![image](https://github.com/user-attachments/assets/816ed69e-0f13-42bc-8081-a4438c353210)
![image](https://github.com/user-attachments/assets/2038369b-fe1e-4e0d-9062-217acee5dc48)

Add payment_id to the bill table and payment_status, payment_day to the payment table, remove paymentType because paymentMethod already exists

https://lucid.app/lucidchart/59061a5b-242e-4474-9552-b10ab093fd66/edit?viewport_loc=-4240%2C-1908%2C4775%2C2236%2C0_0&invitationId=inv_b1bab909-0c4c-4175-b808-4ff15e6d4a4f

**Comment by Ducchinh96** [comment]
![Screenshot 2024-10-11 170819](https://github.com/user-attachments/assets/9f46a566-ff13-4168-9b7e-1f07dc2defa2)

https://lucid.app/lucidchart/6b2a3db5-9c02-4f7e-a08c-eb6566faf8e6/edit?viewport_loc=-1868%2C-650%2C4064%2C2612%2C0_0&invitationId=inv_500adb19-6f12-430e-8e94-1e9b1c110df7
