### ISSUE TITLE
Write Api Document

### ISSUE THREAD

**Issue by nhom1102024** [nhom1102024/MockProject_102024_Nhom1#84]
#### công việc của ngày hôm nay tất cả dev viết api document và khởi tạo dự án: 
-  Hồ Bá Đông sẽ khởi tạo dự án cho bên frontend và code phần layout cho admin trước
-  Nguyễn Thị Ánh Nga tạo dự án cho backend java và cấu hình với sql server
-  Đặng Ngọc Hải tạo dự án cho nodejs và cấu hình với sql server
- mng push code lên cho đúng repository của nhóm nha
- note: bạn nào deploy được database thì báo trong nhóm để mọi người cùng làm chung 1 database
- tất cả các dev  viết api document theo các task api đã phân dưới đây: 
link phân công task: https://docs.google.com/spreadsheets/d/16fXfZCgJ3EKpnYaPgTRtXBlJkDgSxFJS/edit?gid=1431180285#gid=1431180285
- mng viết api dựa theo ERD database của nhóm trong google drive, nếu thiếu mng tự thêm viết thêm nha.
- **mng check mail accept để viết api document bằng postman nếu chưa có mail mn tạo file doc viết xong gửi link vào comment của task này để mình tổng hợp trên postman**
link postman: https://www.postman.com/martian-flare-44482/mocproject-102024-group1/collection/v0ow11q/mockproject-102024-group1?action=share&creator=27401620
- mng điền các tham số cần thiết và url endpoint và mỗi file request mn Add example để cấu hình response trả về nha mn.
- sau khi viết postman ở trên nhớ ctrl + s để lưu lại và xem api document ở đây : https://documenter.getpostman.com/view/27401620/2sAXxS8rKr
-  các bạn cứ làm theo ý mình miễn api document có thể đọc được nha
- **sau khi xong mng comment done và check xong task trong link để mình vào check nha**
- **note:** sau khi có task mng nhớ viết task vào workbreakdown, sau khi xong task mng đẩy sản phẩm của mình lên drive cá nhân để mentor review
- ### dealine : 11h tối hôm nay

**Comment by seaesa** [comment]
https://docs.google.com/document/d/15NOR8m8P2dBRPGgmKwCHQ-fVccKHHXNXtME0w2YC28k/edit?usp=sharing
Done!

**Comment by Dong123333** [comment]
https://docs.google.com/document/d/1L1eGb8wKY-IRuyb6ET3NvZs1HUDt9CKk/edit
Done!

**Comment by haiezdev** [comment]
https://docs.google.com/document/d/1PDvZx9R6pOy6iJzEbvcSEGBIj56FFxQD0M_u-yDSknU/edit?tab=t.0
Done

**Comment by TanHenOtto** [comment]
https://docs.google.com/document/d/1ATkSuJN15SMMJ1Wv2rWD9nHLXPI_10jSjkibDomxxRU/edit?tab=t.0
DONE

**Comment by lainguyentruongvu** [comment]
https://docs.google.com/document/d/1aT0auAM7kQ3hPiLV1OS6_7LH0CtUOt_J/edit?usp=drive_link&ouid=107824023202297874992&rtpof=true&sd=true

**Comment by nhom1102024** [comment]
accept trong mail r convert qua postman thử đi mng

**Comment by Ducchinh96** [comment]
https://docs.google.com/document/d/1IIHc4cdIDw2DnSqQaf787W1c7qXFatAxgFzaMYuoRC0/edit?tab=t.0

Vào Th 2, 14 thg 10, 2024 vào lúc 08:55 nhom1102024 <
***@***.***> đã viết:

**Comment by hovanthang2503** [comment]
https://docs.google.com/document/d/12R_YbUnTRhb7EliukvgfyIy7fgtlysco9wQWuqZjJgQ/edit?usp=sharing
Done

**Comment by TTThanhGiang** [comment]
Done

**Comment by thuyhang2401** [comment]
Done

**Comment by thongmloe** [comment]
[https://docs.google.com/document/d/1v_F6_7rKLYl1gu9r3zQs0WjMcDvTMuQF/edit?usp=sharing&ouid=100818441947313384901&rtpof=true&sd=true](https://docs.google.com/document/d/1v_F6_7rKLYl1gu9r3zQs0WjMcDvTMuQF/edit?usp=sharing&ouid=100818441947313384901&rtpof=true&sd=true)
Done

**Comment by tuankie102** [comment]
done

**Comment by NgaAnhNguyen** [comment]
done

**Comment by ldtdung20it6** [comment]
Done
https://drive.google.com/drive/folders/1x7AW-q1p7c7e929dlyVmeG5dknfUfnzU?usp=sharing

**Comment by HuyNgo000** [comment]
Done
